### ISSUE TITLE
error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Sjoerd82** [Sjoerd82/defender-headunit#2]
Version: 0.1.0-777-g39c2807

[ MPD  ] DBUS event received: player
[SYSTEM] Detected MPD event: player. Retrieving MPD state.
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 230, in maybe_handle_message
  File "./hu.py", line 441, in cb_mpd_event
    status = mpdc.mpc_get_status()
  File "/mnt/PIHU_APP/defender-headunit/hu_mpd.py", line 356, in mpc_get_status
    self.mpdc.command_list_ok_begin()
  File "usr/lib/python2.7/site-packages/mpd.py", line 583, in command_list_ok_begin
  File "usr/lib/python2.7/site-packages/mpd.py", line 279, in _write_command
  File "usr/lib/python2.7/site-packages/mpd.py", line 259, in _write_line
  File "usr/lib/python2.7/socket.py", line 307, in flush
error: [Errno 32] Broken pipe

**Comment by Sjoerd82** [comment]
Trying: mpd.conf connection_timeout              "2000000"
seems to work so far...

**Comment by Sjoerd82** [comment]
Running for 10+ hrs without problems.. still this is a workaround for a connection problem that needs to be solved in code instead.
